package de.timweb.android.gpx;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

import de.timweb.android.track.Track;
import de.timweb.android.track.TrackManager;
import de.timweb.android.util.LocationReader;
import de.timweb.android.util.LocationReader.LocationAndSteps;

import android.content.Context;
import android.os.Environment;

public class GPXExporter {

	private static void doinBackground(int trackid, Context context) {
		File sdCard = Environment.getExternalStorageDirectory();
		File dir = new File(sdCard.getAbsolutePath() + "/BlueTrack");
		dir.mkdirs();

		Track track = TrackManager.getLiteTrack(context, trackid);
		String date = track.getDay();
		
		File file = new File(dir, "track_"+trackid+"_("+date+").gpx");

		FileWriter f;
		try {
			f = new FileWriter(file);
		} catch (IOException e1) {
			e1.printStackTrace();
			return;
		}
		BufferedWriter writer = new BufferedWriter(f);
		try {
			writeLocations(writer, trackid, context);
		} catch (IOException e) {
			e.printStackTrace();
		}
		try {
			writer.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		try {
			f.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public static void writeToGPXFile(final int trackid, final Context context) {
		new Thread() {
			@Override
			public void run() {
				doinBackground(trackid,context);
			}

		}.start();
	}

	private static void writeLocations(BufferedWriter writer, int trackid,
			Context context) throws IOException {
		writer.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"yes\"?>"
				+ "\n"
				+ "<gpx"
				+ "\n"
				+ "version=\"1.1\""
				+ "\n"
				+ "creator=\"BlueTrack - AndroidApp\""
				+ "\n"
				+ "xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"	"
				+ "\n"
				+ "xmlns:topografix=\"http://www.topografix.com/GPX/Private/TopoGrafix/0/1\""
				+ "\n"
				+ "xmlns=\"http://www.topografix.com/GPX/1/1\""
				+ "\n"
				+ "xsi:schemaLocation=\"http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd\">"
				+ "\n");

		writer.write("<name>BlueTrack - GPS-Track</name>\n");
		writer.write("<desc>This File was generated by our Android-App BlueTrack</desc>\n");
		writer.write("<author>Tim Schmiedl &#38; Milos Babic</author>\n");
		writer.write("<email>bluetrack@timweb.de</email>\n");
		writer.write("<url>http://www.timweb.de/android</url>\n");
		writer.write("<keywords>GPS,Track,BlueTrack,Android,timweb.de</keywords>\n");
		
		ArrayList<LocationAndSteps> locs = LocationReader.getLocations(context,
				trackid);
		if (locs.size() == 0)
			return;

		// <<Begin Start&Endpunkte>>
		StringBuilder str = new StringBuilder();
		str.append("<wpt lat=\"");
		str.append(locs.get(0).getLatitude());
		str.append("\" lon=\"");
		str.append(locs.get(0).getLongitude());
		str.append("\">\n\t<ele>");
		str.append((int) locs.get(0).getAltitude());
		str.append("</ele>\n\t<name>Start</name>\n\t<sym>Start</sym>\n");
		str.append("</wpt>\n");
		writer.write(str.toString());

		str = new StringBuilder();
		str.append("<wpt lat=\"");
		str.append(locs.get(locs.size() - 1).getLatitude());
		str.append("\" lon=\"");
		str.append(locs.get(locs.size() - 1).getLongitude());
		str.append("\">\n\t<ele>");
		str.append((int) locs.get(locs.size() - 1).getAltitude());
		str.append("</ele>\n\t<name>End</name>\n\t<sym>End</sym>\n");
		str.append("</wpt>\n");
		writer.write(str.toString());
		// <<End Start&Endpunkte>>

		// <<Begin Locations>>
		writer.write("<trk>\n");
		writer.write("<trkseg>\n");

		str = new StringBuilder();
		for (LocationAndSteps l : locs) {
			str.append("<trkpt lat=\"");
			str.append(l.getLatitude());
			str.append("\" lon=\"");
			str.append(l.getLongitude());
			str.append("\">\n\t<ele>");
			str.append((int) l.getAltitude());
			str.append("</ele>\n\t<time>");
			str.append(l.getTime());
			str.append("</time>\n\t<speed>");
			str.append(l.getSpeed());
			str.append("</speed>\n\t<cmt>");
			str.append("steps:" + l.getSteps());
			str.append("</cmt>\n</trkpt>\n");

			writer.write(str.toString());
			str = new StringBuilder();
		}

		writer.write("</trkseg>\n");
		writer.write("</trk>\n");
		// <<End Locations>>

		writer.write("<extensions></extensions>\n");
		writer.write("</gpx>");
	}
}
